### ISSUE TITLE
Outdated glr file format

### ISSUE THREAD

**Issue by DrJamesC25** [Luctaris/blender-import-glr#5]
Hi, I'm trying to use your plugin with Blender. I have some glr files I got from Rosalie's Mupen GUI that ripped scenes from Kirby 64, I'm trying to get the models of the stone cutter Kirby. When I used your plugin to open the glr files I got this error:

Python: Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.91\2.91\scripts\addons\io_import_glr\__init__.py", line 170, in execute
    return import_glr.load(context, **keywords)
  File "C:\Program Files\Blender Foundation\Blender 2.91\2.91\scripts\addons\io_import_glr\import_glr.py", line 34, in load
    ob = load_glr(filepath, triangle_options)
  File "C:\Program Files\Blender Foundation\Blender 2.91\2.91\scripts\addons\io_import_glr\import_glr.py", line 67, in load_glr
    return GlrImporter(fb, texture_dir, triangle_options).load()
  File "C:\Program Files\Blender Foundation\Blender 2.91\2.91\scripts\addons\io_import_glr\import_glr.py", line 85, in load
    self.load_header()
  File "C:\Program Files\Blender Foundation\Blender 2.91\2.91\scripts\addons\io_import_glr\import_glr.py", line 98, in load_header
    raise RuntimeError(f'Outdated glr file format detected ({version}), please update the glr import addon')
RuntimeError: Outdated glr file format detected (1), please update the glr import addon

location: <unknown location>:-1

If you could give any assistance in fixing this I'd really appreciate it.

**Comment by Luctaris** [comment]
Is there any reason why you are still using Blender 2.91? The plugin had a software bug up until Blender 3.5 and on-wards, so I recommend that you try the latest release as of this post (Blender 3.6 LTS)

**Comment by DrJamesC25** [comment]
I'll use the recent version and see how that works. Ty for getting back to me.

**Comment by Luctaris** [comment]
Did updating Blender resolve the problem, or are you still having the same issue?

**Comment by DrJamesC25** [comment]
Python: Traceback (most recent call last):
  File "C:\Users\James\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\io_import_glr\__init__.py", line 170, in execute
    return import_glr.load(context, **keywords)
  File "C:\Users\James\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\io_import_glr\import_glr.py", line 34, in load
    ob = load_glr(filepath, triangle_options)
  File "C:\Users\James\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\io_import_glr\import_glr.py", line 67, in load_glr
    return GlrImporter(fb, texture_dir, triangle_options).load()
  File "C:\Users\James\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\io_import_glr\import_glr.py", line 85, in load
    self.load_header()
  File "C:\Users\James\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\io_import_glr\import_glr.py", line 98, in load_header
    raise RuntimeError(f'Outdated glr file format detected ({version}), please update the glr import addon')
RuntimeError: Outdated glr file format detected (1), please update the glr import addon


This is the error I got using the current version of Blender.

**Comment by Luctaris** [comment]
Hmmm... seems similar to the one you received on Blender 2.91. Are you building the source code from the repo, or using the 1,0 release package?

**Comment by DrJamesC25** [comment]
I downloaded the zip, got the files out, and then sent te import io folder to a zip and installed by locating it in the Add Ons install menu

**Comment by Luctaris** [comment]
I could be wrong, but it seems like you're using the master repo code which includes experimental changes and modifications to the glr format. Try downloading and replacing the installed plugin you have with this one: https://github.com/Luctaris/blender-import-glr/releases/download/Releases/io_import_glr_v1_0_0.zip

**Comment by DrJamesC25** [comment]
It's having some trouble installing this through the AddOn menu. It says it is being installed, but it is not appearing in the Menu

**Comment by Luctaris** [comment]
Completely uninstall/remove the version you had installed and select the .zip file I linked above when re-installing it.

**Comment by DrJamesC25** [comment]
I've removed it, and can even see the import glr in the addons folder in my 3.6 install folder. But it is not showing in the addons menu in blender. Let me try this with version 3.5, it worked in that version right?

**Comment by Luctaris** [comment]
Technically it should work on any Blender version after 2.80, but I would recommend using Blender 3.5+ only because of a bug that was fixed. While you're still on 3.6, try manually placing and installing the addon. Extract the zip linked above to your %appdata%\Blender Foundation\Blender\3.6\scripts\addons folder. You can name the folder `io_import_glr`.
